# -*- coding: utf-8 -*-
"""efficientad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f78dOZ92vYf5D63Dv-GJ1MRQLCVXawzV
"""

from google.colab import drive
drive.mount('/content/drive')

import os
# Çalışma dizini
WORKDIR = '/content/efficientad'
DATASET_DIR = '/content/drive/MyDrive/processed'  # senin processed klasörün

# Repo’yu klonla
!git clone https://github.com/nelson1425/EfficientAD.git {WORKDIR}
os.chdir(WORKDIR)

# PyTorch + CUDA
!pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu118
# Diğer bağımlılıklar
!pip install tqdm scikit-learn tifffile pillow

# Çalışma dizininde mvtec_ad klasörünü oluşturun
!rm -rf mvtec_ad
!mkdir -p mvtec_ad/wood
!ln -s "{DATASET_DIR}/train"       mvtec_ad/wood/train
!ln -s "{DATASET_DIR}/test"        mvtec_ad/wood/test
!ln -s "{DATASET_DIR}/ground_truth" mvtec_ad/wood/ground_truth

!python efficientad.py \
  -d mvtec_ad \
  -s wood \
  -o output/wood_small \
  -m small \
  -w models/teacher_small.pth \
  -a mvtec_ad \
  -i none \
  -t 70000

import os
import numpy as np
import torch
import torch.nn as nn
from PIL import Image
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from efficientad import (
    predict, map_normalization, teacher_normalization,
    get_autoencoder, get_pdn_small
)
from skimage.filters import threshold_otsu, gaussian
from skimage.transform import resize
from sklearn.metrics import accuracy_score, f1_score, jaccard_score, precision_score, recall_score, roc_auc_score
import matplotlib.pyplot as plt
from scipy import ndimage

# Ayarlar
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
OUT_CH = 384
IMG_SIZE = 256
DATASET_DIR = '/content/drive/MyDrive/processed'
MODEL_DIR = 'output/wood_small/trainings/mvtec_ad/wood'
GT_DIR = os.path.join(DATASET_DIR, 'ground_truth')
BATCH_SIZE = 4  # Batch size artışı

# Gelişmiş Transform
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])

# WoodTest Dataset - İyileştirilmiş
class WoodTest(torch.utils.data.Dataset):
    def __init__(self, img_dir, gt_dir, transform):
        self.samples = []
        self.img_dir = img_dir
        self.gt_dir = gt_dir
        self.transform = transform

        # Veri setini oluştur
        for sub in ['good', 'defect']:
            folder = os.path.join(img_dir, sub)
            if not os.path.exists(folder):
                print(f"Uyarı: {folder} klasörü bulunamadı!")
                continue

            for fn in os.listdir(folder):
                if fn.lower().endswith(('.png','.jpg','.jpeg','.tif','.tiff')):
                    img_path = os.path.join(folder, fn)

                    # Defect içinse mask dosyasını da kontrol et
                    if sub == 'defect':
                        stem, ext = os.path.splitext(fn)
                        gt_fname = f"{stem}_mask{ext}"
                        gt_path = os.path.join(gt_dir, 'defect', gt_fname)

                        if not os.path.exists(gt_path):
                            print(f"Uyarı: {gt_path} mask dosyası bulunamadı!")
                            gt_path = None
                    else:
                        gt_path = None

                    self.samples.append((img_path, gt_path, sub))

        print(f"Toplam {len(self.samples)} örnek bulundu.")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, gt_path, class_name = self.samples[idx]

        # Resmi yükle ve transform et
        img = Image.open(img_path).convert('RGB')
        img_tensor = self.transform(img)  # [3, H, W]

        # Ground truth mask oluştur
        if gt_path and os.path.exists(gt_path):
            mask = Image.open(gt_path).convert('L')
            mask = mask.resize((IMG_SIZE, IMG_SIZE), Image.Resampling.NEAREST)
            gt = np.array(mask) > 0  # Binary mask
        else:
            # 'good' sınıfı veya eksik mask için boş mask oluştur
            gt = np.zeros((IMG_SIZE, IMG_SIZE), dtype=bool)

        return img_tensor, gt, img_path, class_name

# Modelleri yükle (safe_load fonksiyonu)
def safe_load(path):
    try:
        checkpoint = torch.load(path, map_location=DEVICE, weights_only=False)
        if isinstance(checkpoint, dict) and 'state_dict' in checkpoint:
            return checkpoint['state_dict']
        elif isinstance(checkpoint, dict):
            return checkpoint
        return checkpoint
    except Exception as e:
        print(f"Model yüklenirken hata: {e}")
        return None

# Post-processing fonksiyonları
def post_process_anomaly_map(anomaly_map, sigma=2):
    """Anomali haritası için post-processing"""
    # Gaussian smoothing uygula
    smoothed = gaussian(anomaly_map, sigma=sigma)

    # Morfolojik işlemler (opsiyonel)
    # Gürültüyü azaltmak için küçük açma işlemi
    return smoothed

def adaptive_thresholding(anomaly_scores, gt_labels=None, percentile=95):
    """
    Uyarlanabilir eşikleme stratejisi
    Eğer gt_labels verilmişse, F1 skoru maksimize eden eşiği bulur
    Aksi takdirde belirlenen yüzdelik dilimi kullanır
    """
    if gt_labels is not None:
        # Grid search ile en iyi eşik değerini bul
        best_f1 = 0
        best_threshold = 0
        thresholds = np.linspace(np.min(anomaly_scores), np.max(anomaly_scores), 100)

        for threshold in thresholds:
            preds = (anomaly_scores > threshold).astype(np.uint8)
            f1 = f1_score(gt_labels, preds)

            if f1 > best_f1:
                best_f1 = f1
                best_threshold = threshold

        return best_threshold
    else:
        # Belirlenen yüzdelik dilim ile eşik değerini belirle
        return np.percentile(anomaly_scores, percentile)

# Görselleştirme fonksiyonu
def visualize_results(images, gt_masks, anomaly_maps, predictions, save_dir="results"):
    """Tahminleri ve ground truth'u görselleştir"""
    os.makedirs(save_dir, exist_ok=True)

    for i, (img, gt, amap, pred) in enumerate(zip(images, gt_masks, anomaly_maps, predictions)):
        plt.figure(figsize=(15, 5))

        plt.subplot(141)
        plt.title("Original Image")
        plt.imshow(img)
        plt.axis('off')

        plt.subplot(142)
        plt.title("Ground Truth")
        plt.imshow(gt, cmap='gray')
        plt.axis('off')

        plt.subplot(143)
        plt.title("Anomaly Map")
        plt.imshow(amap, cmap='jet')
        plt.axis('off')

        plt.subplot(144)
        plt.title("Prediction")
        plt.imshow(pred, cmap='gray')
        plt.axis('off')

        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, f"result_{i}.png"))
        plt.close()

# Modelleri oluştur ve yükle
teacher = get_pdn_small(OUT_CH).to(DEVICE).eval()
student = get_pdn_small(2*OUT_CH).to(DEVICE).eval()
autoencoder = get_autoencoder(OUT_CH).to(DEVICE).eval()

# Checkpoint'leri yükle
teacher_ckpt = safe_load(os.path.join(MODEL_DIR, 'teacher_final.pth'))
student_ckpt = safe_load(os.path.join(MODEL_DIR, 'student_final.pth'))
ae_ckpt = safe_load(os.path.join(MODEL_DIR, 'autoencoder_final.pth'))

if teacher_ckpt is not None:
    if isinstance(teacher_ckpt, nn.Module):
        teacher = teacher_ckpt
    else:
        teacher.load_state_dict(teacher_ckpt)

if student_ckpt is not None:
    if isinstance(student_ckpt, nn.Module):
        student = student_ckpt
    else:
        student.load_state_dict(student_ckpt)

if ae_ckpt is not None:
    if isinstance(ae_ckpt, nn.Module):
        autoencoder = ae_ckpt
    else:
        autoencoder.load_state_dict(ae_ckpt)

# Normalizasyon işlemleri
print("Teacher normalizasyonu hesaplanıyor...")
train_loader = DataLoader(
    ImageFolder(os.path.join('mvtec_ad','wood','train'), transform=transform),
    batch_size=BATCH_SIZE, shuffle=False
)
teacher_mean, teacher_std = teacher_normalization(teacher, train_loader)

print("Map normalizasyonu hesaplanıyor...")
val_loader = DataLoader(
    ImageFolder(os.path.join('mvtec_ad','wood','train'), transform=transform),
    batch_size=BATCH_SIZE, shuffle=False
)
q_st0, q_st1, q_ae0, q_ae1 = map_normalization(
    val_loader, teacher, student, autoencoder, teacher_mean, teacher_std
)

# Test veri setini oluştur
test_ds = WoodTest(os.path.join('mvtec_ad','wood','test'), GT_DIR, transform)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)

# Anomali haritalarını ve metrikleri hesapla
all_pixel_scores = []
all_pixel_gts = []
all_image_scores = []
all_image_labels = []
sample_images = []
sample_gt_masks = []
sample_anomaly_maps = []

print("\nAnomali tespiti yapılıyor...")
with torch.no_grad():
    for i, batch in enumerate(test_loader):
        imgs, gt_masks, img_paths, class_names = batch
        imgs = imgs.to(DEVICE)

        batch_size = imgs.size(0)

        # Anomali haritalarını tahmin et
        batch_maps = []
        for j in range(batch_size):
            combined_map, st_map, ae_map = predict(
                imgs[j:j+1], teacher, student, autoencoder,
                teacher_mean, teacher_std,
                q_st0, q_st1, q_ae0, q_ae1
            )
            batch_maps.append(combined_map[0, 0].cpu().numpy())

        # Her görüntü için işlem yap
        for j in range(batch_size):
            anomaly_map = batch_maps[j]
            gt_mask_np = gt_masks[j].numpy()

            # Post-processing uygula
            processed_map = post_process_anomaly_map(anomaly_map)

            # Görüntü seviyesinde skor (maksimum anomali skoru)
            image_score = float(np.max(processed_map))
            image_label = 0 if class_names[j] == 'good' else 1

            # Skorları ve etiketleri kaydet
            all_image_scores.append(image_score)
            all_image_labels.append(image_label)

            # Anomali haritasını ground truth ile aynı boyuta getir
            anomaly_map_resized = resize(processed_map, gt_mask_np.shape,
                                         mode='reflect', anti_aliasing=True)

            # Piksel bazlı tahminleri ve gerçek değerleri kaydet
            all_pixel_scores.append(anomaly_map_resized.flatten())
            all_pixel_gts.append(gt_mask_np.flatten())

            # Bazı örnekleri görselleştirme için kaydet
            if len(sample_images) < 5 and image_label == 1:  # Defect örnekleri
                # Orijinal görüntüyü PIL'e çevir
                img_np = imgs[j].cpu().numpy().transpose(1, 2, 0)
                img_np = (img_np * np.array([0.229, 0.224, 0.225]) +
                          np.array([0.485, 0.456, 0.406]))
                img_np = np.clip(img_np, 0, 1)

                sample_images.append(img_np)
                sample_gt_masks.append(gt_mask_np)
                sample_anomaly_maps.append(anomaly_map_resized)

        # İlerlemeyi göster
        if (i+1) % 5 == 0 or i == len(test_loader) - 1:
            print(f"İşleniyor: {min((i+1)*BATCH_SIZE, len(test_ds))}/{len(test_ds)}")

# Piksel skorlarını birleştir
pixel_scores = np.concatenate(all_pixel_scores)
pixel_gts = np.concatenate(all_pixel_gts)

# Boyut kontrolü
print(f"Toplam piksel skoru sayısı: {len(pixel_scores)}")
print(f"Toplam ground truth sayısı: {len(pixel_gts)}")

# İyileştirilmiş eşikleme: F1'i maksimize eden eşik değerini bul
print("\nEn iyi eşik değeri hesaplanıyor...")
optimal_threshold = adaptive_thresholding(pixel_scores, pixel_gts)
print(f"Optimal eşik değeri: {optimal_threshold:.6f}")

# Binary tahminleri oluştur
pixel_preds = (pixel_scores > optimal_threshold).astype(np.uint8)

# Metrikleri hesapla
pixel_acc = accuracy_score(pixel_gts, pixel_preds)
pixel_precision = precision_score(pixel_gts, pixel_preds)
pixel_recall = recall_score(pixel_gts, pixel_preds)
pixel_f1 = f1_score(pixel_gts, pixel_preds)
pixel_iou = jaccard_score(pixel_gts, pixel_preds)

# ROC AUC hesapla (piksel seviyesinde)
try:
    pixel_auc = roc_auc_score(pixel_gts, pixel_scores)
except:
    pixel_auc = 0.0

# Görüntü seviyesinde metrikleri hesapla
# Görüntü seviyesi için optimal eşik
image_threshold = adaptive_thresholding(all_image_scores, all_image_labels)
image_preds = (np.array(all_image_scores) > image_threshold).astype(np.uint8)
image_acc = accuracy_score(all_image_labels, image_preds)
image_f1 = f1_score(all_image_labels, image_preds)

# Görüntü seviyesinde ROC AUC hesapla
try:
    image_auc = roc_auc_score(all_image_labels, all_image_scores)
except:
    image_auc = 0.0

# Sample tahminlerini oluştur (visualize için)
sample_preds = [(s > optimal_threshold).astype(np.uint8) for s in sample_anomaly_maps]

# Görselleştir
if sample_images:
    visualize_results(sample_images, sample_gt_masks, sample_anomaly_maps, sample_preds)

print("\n===== SONUÇLAR =====")
print("Piksel Seviyesi Metrikler:")
print(f"✅ Accuracy: {pixel_acc:.4f}")
print(f"✅ Precision: {pixel_precision:.4f}")
print(f"✅ Recall: {pixel_recall:.4f}")
print(f"✅ F1 Score: {pixel_f1:.4f}")
print(f"✅ IoU (Jaccard): {pixel_iou:.4f}")
print(f"✅ ROC AUC: {pixel_auc:.4f}")

print("\nGörüntü Seviyesi Metrikler:")
print(f"✅ Accuracy: {image_acc:.4f}")
print(f"✅ F1 Score: {image_f1:.4f}")
print(f"✅ ROC AUC: {image_auc:.4f}")

!cp output/wood_small/trainings/mvtec_ad/wood/*.pth /content/drive/MyDrive/efficientad_models/

from google.colab import files
files.download('output/wood_small/trainings/mvtec_ad/wood/teacher_final.pth')
files.download('output/wood_small/trainings/mvtec_ad/wood/student_final.pth')
files.download('output/wood_small/trainings/mvtec_ad/wood/autoencoder_final.pth')