# -*- coding: utf-8 -*-
"""uninet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riVAetBb8w8Kah6VbmKzSBSLHU2AJdq9
"""

# Google Drive'a bağlanma
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# UniNet reposunu temiz bir şekilde klonlama
!rm -rf UniNet
!git clone https://github.com/pangdatangtt/UniNet.git
# %cd UniNet

# Gerekli paketleri kurma
!pip install -q matplotlib numpy opencv-python-headless pandas pillow scikit-image scikit-learn scipy tabulate torch torchvision tqdm ptflops

# Datasets.py dosyasını düzenleme
import re

# Dosyayı okuma
with open('datasets.py', 'r') as f:
    datasets_content = f.read()

# mvtec_list'i değiştirme
datasets_content = re.sub(r'mvtec_list = \[.*?\]', 'mvtec_list = ["wood"]', datasets_content, flags=re.DOTALL)

# Yol düzeltmesi
datasets_content = datasets_content.replace(
    "self.dataset_path = '../data/' + dataset",
    "self.dataset_path = './data/' + dataset"
)

# Wood'u gri tonlamalı görüntü olarak işaretleme
datasets_content = datasets_content.replace(
    "if self.class_name in ['zipper', 'screw', 'grid']:",
    "if self.class_name in ['zipper', 'screw', 'grid', 'wood']:"
)

# Değişikliği kaydetme
with open('datasets.py', 'w') as f:
    f.write(datasets_content)

print("Datasets.py dosyası başarıyla güncellendi.")

# Zamanlayıcı ekleme (train_unsupervisedAD.py)
with open('train_unsupervisedAD.py', 'r') as f:
    train_content = f.read()

# Zamanlayıcı kodu
timer_code = '''
import time

# Eğitim başlangıç zamanını kaydet
training_start_time = time.time()
max_training_time = 20 * 60  # 20 dakika

def check_time():
    elapsed = time.time() - training_start_time
    if elapsed > max_training_time:
        print(f"\\n20 dakikalık eğitim süresi doldu ({elapsed:.2f} saniye).")
        print("Eğitim durduruldu ve en iyi model kaydedildi.")
        return True
    return False
'''

# Zamanlayıcı kodunu ekle
if 'training_start_time = time.time()' not in train_content:
    train_content = timer_code + '\n' + train_content

# Epoch başına kontrol ekle
if 'check_time()' not in train_content:
    train_content = train_content.replace(
        'for epoch in range(1, c.epochs + 1):',
        'for epoch in range(1, c.epochs + 1):\n        if check_time():\n            break'
    )

# Değişikliği kaydet
with open('train_unsupervisedAD.py', 'w') as f:
    f.write(train_content)

print("Eğitim dosyası 20 dakika zamanlayıcı ile güncellendi.")

# Veri seti için klasör yapısını oluşturma
import os

os.makedirs('data/mvtec/wood/train/good', exist_ok=True)
os.makedirs('data/mvtec/wood/test/good', exist_ok=True)
os.makedirs('data/mvtec/wood/ground_truth', exist_ok=True)

# Varsayılan olarak defect klasörünü oluşturma (anomali türünüzü buraya ekleyin)
os.makedirs('data/mvtec/wood/test/defect', exist_ok=True)
os.makedirs('data/mvtec/wood/ground_truth/defect', exist_ok=True)

print("Veri seti klasör yapısı oluşturuldu.")

# Veri setini kopyalama (YOLLARINIZI DEĞİŞTİRİN!)
!cp -r /content/drive/MyDrive/processed/wood/train/good/* data/mvtec/wood/train/good/
!cp -r /content/drive/MyDrive/processed/wood/test/good/* data/mvtec/wood/test/good/
!cp -r /content/drive/MyDrive/processed/wood/test/defect/* data/mvtec/wood/test/defect/
!cp -r /content/drive/MyDrive/processed/wood/ground_truth/defect/* data/mvtec/wood/ground_truth/defect/

print("Veri seti dosyaları kopyalandı.")

# Son kontroller
print("Son kontrol")
print("mvtec_list = ", end="")
!grep -m 1 "mvtec_list" datasets.py

# Eğitimi başlatma (1000 epoch, 20 dakika sonra otomatik duracak)
!python main.py --setting oc --dataset "MVTec AD" --epochs 1000

# Eğitilmiş modeli test etme
!python main.py --setting oc --dataset "MVTec AD" --load_ckpts

from google.colab import files

# Dosyanın varlığını kontrol et
!ls -la "/content/UniNet/ckpts/MVTec AD/wood/BEST_P_PRO.pth"

# Dosyayı sıkıştır (büyük olabilir)
!mkdir -p /content/model_weights
!cp -r "/content/UniNet/ckpts/MVTec AD/wood" /content/model_weights/
!cd /content && zip -r model_weights.zip model_weights

# Dosyayı indir
files.download('/content/model_weights.zip')

# 1. Gerekli kütüphaneleri içe aktarma
import os
import sys
import copy
import numpy as np
import torch
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, f1_score, roc_curve, auc

# 2. Python yoluna UniNet klasörünü ekleyin
sys.path.append('/content/UniNet')

# 3. UniNet'ten gerekli modülleri içe aktarma
from UniNet_lib.model import UniNet
from UniNet_lib.resnet import wide_resnet50_2
from UniNet_lib.DFS import DomainRelated_Feature_Selection
from utils import load_weights, to_device
from datasets import MVTecDataset

# 4. Config sınıfını tanımlama
class Config:
    def __init__(self):
        self._class_ = "wood"
        self.image_size = 256
        self.center_crop = 256
        self.batch_size = 1
        self.T = 2
        self.weighted_decision_mechanism = True
        self.default = 0.3
        self.alpha = 0.01
        self.beta = 3e-05

# 5. Test veri setini hazırlama
c = Config()
test_dataset = MVTecDataset(c, is_train=False)
test_dataloader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=False)

# 6. Modeli hazırlama
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Kullanılan cihaz: {device}")

Source_teacher, bn = wide_resnet50_2(c, pretrained=True)
Source_teacher.layer4 = None
Source_teacher.fc = None

from UniNet_lib.de_resnet import de_wide_resnet50_2
student = de_wide_resnet50_2(pretrained=False)

DFS = DomainRelated_Feature_Selection()
[Source_teacher, bn, student, DFS] = to_device([Source_teacher, bn, student, DFS], device)
Target_teacher = copy.deepcopy(Source_teacher)

ckpt_path = os.path.join("./ckpts", "MVTec AD", "wood")
print(f"Ağırlıkları yüklüyorum: {ckpt_path}/BEST_P_PRO.pth")
new_state = load_weights([Target_teacher, bn, student, DFS], ckpt_path, 'BEST_P_PRO')
Target_teacher = new_state['tt']
bn = new_state['bn']
student = new_state['st']
DFS = new_state['dfs']

model = UniNet(c, Source_teacher.cuda().eval(), Target_teacher, bn, student, DFS)
model.eval()

# 7. Tüm test veri seti için tahminleri toplama
print("Tahminler hesaplanıyor...")
img_scores = []
gt_list = []

with torch.no_grad():
    for x, y, mask in test_dataloader:
        x = x.to(device)
        result = model(x)

        # Model çıktısını doğru şekilde işle (çıktı bir liste olduğu için)
        # Test.py dosyasından anomali skoru hesaplama yöntemini inceleyerek:
        if isinstance(result, tuple):
            score_patches = result[0]
            # Eğer score_patches bir tensor ise
            if isinstance(score_patches, torch.Tensor):
                img_score = torch.max(score_patches).cpu().item()
            # Eğer score_patches bir liste ise
            elif isinstance(score_patches, list):
                # Listenin her elemanının maksimumunu al
                scores = [torch.max(patch).cpu().item() for patch in score_patches if isinstance(patch, torch.Tensor)]
                img_score = max(scores) if scores else 0.0
        else:
            # Eğer model çıktısı başka bir formatta ise
            print(f"Model çıktı tipi: {type(result)}")
            img_score = 0.0

        img_scores.append(img_score)
        gt_list.append(y.item())

img_scores = np.array(img_scores)
gt_list = np.array(gt_list)
# 8. Optimal threshold hesaplama
precision, recall, thresholds = precision_recall_curve(gt_list, img_scores)
f1_scores = 2 * precision * recall / (precision + recall + 1e-8)
best_threshold_idx = np.argmax(f1_scores)
best_threshold = thresholds[best_threshold_idx]
best_f1 = f1_scores[best_threshold_idx]

print(f"En İyi Threshold: {best_threshold:.4f}")
print(f"Bu Threshold'da F1 Skoru: {best_f1:.4f}")

# 9. ROC Eğrisi çizme
fpr, tpr, _ = roc_curve(gt_list, img_scores)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(12, 5))

# ROC Eğrisi
plt.subplot(1, 2, 1)
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC eğrisi (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Yanlış Pozitif Oranı')
plt.ylabel('Doğru Pozitif Oranı')
plt.title('ROC Eğrisi')
plt.legend(loc="lower right")

# Precision-Recall Eğrisi
plt.subplot(1, 2, 2)
plt.plot(recall, precision, color='blue', lw=2, label='Precision-Recall eğrisi')
plt.scatter(recall[best_threshold_idx], precision[best_threshold_idx], marker='o', color='red',
           label=f'En iyi threshold = {best_threshold:.4f}')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Eğrisi')
plt.legend(loc="lower left")

plt.tight_layout()
plt.savefig('threshold_analizi.png')
plt.show()

print(f"Analiz tamamlandı. Görsel kaydedildi: threshold_analizi.png")